services:
  frontend:
    image: redes-frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3030:3030
    # Aqui se define como el volumen del container en el cual se guardaran los cambios
    # En mi caso es de development asi que este me sirve
    volumes:
      - './Frontend:/app'
      - './Frontend/node_modules:/app/node_modules'
    depends_on:
      - client
    networks:
      - networks-p1
  client:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
    - 6363:6363
    volumes:
      - './Backend:/client'
      - './Backend/node_modules:/client/node_modules'
    networks:
      - networks-p1
networks:
  networks-p1:
    driver: bridge

volumes:
  node_modules:
    driver: local